//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KohaKai
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog
    {
        public int id { get; set; }
        public string author { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string title { get; set; }
        //[DataType(DataType.MultilineText)] 
        public string body { get; set; }
    }
}
